<?php

$this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'pupil-results-grid',
	'type'=>'bordered condensed',
	'template'=>'{summary}{items}',
	'ajaxUpdate'=>false,
	'dataProvider'=>$dataProvider,
	'rowCssClassExpression'=>array($component,'getRowCss'),
	'columns'=>array(
		array(
		'name'=>'subject',
		'header'=>'Subject',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		//'type'=>'raw',
		),
		array(
		'name'=>'set_code',
		'header'=>'Class',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		//'type'=>'raw',
		),
		array(
		'name'=>'teacher',
		'header'=>'Teacher',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		//'type'=>'raw',
		'visible'=>$hasMisAccess,
		),
		array(
		'name'=>'qualification',
		'header'=>'Qualification',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		//'type'=>'raw',
		),
		array(
		'name'=>'no_gcses',
		'header'=>($model->mode=='equivalent') ? 'No. | Code' : 'No.',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		'value'=>array($component,'renderNoGCSEValue'),
		'type'=>'raw',
		),
		/*
		array(
		'name'=>'discount_code',
		'header'=>'Discount<br>Code',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		'type'=>'raw',
		'visible'=>($model->mode=='equivalent'),
		),
		*/
		array(
		'name'=>'dcp_result',
		'header'=>'DCP',
		'cssClassExpression'=>array($component,'getCellCssDcpResult'),
		//'type'=>'raw',
		),
		array(
		'name'=>'target_result',
		'header'=>'Target',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		//'type'=>'raw',
		),
		array(
		'name'=>'dcp_standardised_points',
		'header'=>'DCP<br>Score',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		'value'=>array($component,'getDcpDiscount'),
		//'htmlOptions'=>array('width'=>'500px'),
		'type'=>'raw',
		),

		array(
		'name'=>'target_standardised_points',
		'header'=>'Target<br>Score',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		'value'=>array($component,'getTargetDiscount'),
		'type'=>'raw',
		),
		array(
		'name'=>'diff',
		'header'=>'Diff<br>Score',
		'cssClassExpression'=>array($component,'getCellCssDcpResult'),
		'type'=>'raw',
		),
		array(
		'name'=>'dcp_residual',
		'header'=>'DCP<br>Residual',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		'type'=>'raw',
		),
		array(
		'name'=>'target_residual',
		'header'=>'Target<br>Residual',
		//'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		'type'=>'raw',
		),
		array(
		'name'=>'residual_diff',
		'header'=>'Diff<br>Residual',
		'cssClassExpression'=>array($component,'getCellCssResidualDiff'),
		'type'=>'raw',
		),
		array(
		'name'=>'subject_average_aps',
		'header'=>'Subj Av',
		//'cssClassExpression'=>array($component,'getCellCssResidualDiff'),
		'type'=>'raw',
		'visible'=>false,
		),
		array(
		'name'=>'subject_average_aps_diff',
		'header'=>'Diff',
		'cssClassExpression'=>array($component,'getCellCssResidualDiff'),
		'type'=>'raw',
		'visible'=>false,
		),
		array(
		'name'=>'dcp_discount',
		'header'=>'DCP',
		//'cssClassExpression'=>array($component,'getCellCssResidualDiff'),
		//'type'=>'raw',
		'visible'=>false,
		),
		array(
		'name'=>'target_discount',
		'header'=>'Target',
		//'cssClassExpression'=>array($component,'getCellCssResidualDiff'),
		//'type'=>'raw',
		'visible'=>false,
		),
	),
)); ?>

<?php if($model->mode=='equivalent'):?>
<p><strong>No. | Code</strong> - The number of GCSEs the subject is worth | The discount code if applicable <i class='icon-ok-sign'></i> - The eligible point score</p>
<?php else:?>
<p><strong>No.</strong> - The number of GCSEs the subject is worth</p>
<?endif;?>
