<?php // $gridId, $dataProvider and $component are available to this view
$showTargets=false;
$this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>$gridId,
	'template'=>'{summary}{items}',
	'dataProvider'=>$dataProvider,
	'columns'=>array(
			//DCPs
			array(
			'name'=>'col1',
			'header'=>'Subject',
			'type'=>'raw',
		),
		array(
			'name'=>'col2',
			'header'=>'DCP<br>%<br>A*-A',
			'cssClassExpression'=>array($component,'getCellCssAstarToA'),
			'type'=>'raw',
		),
		array(
			'name'=>'col3',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellCssAstarToA'),
		),
		array(
			'name'=>'col4',
			'header'=>'%<br><span class="label">A*-C</span>',
			'cssClassExpression'=>array($component,'getCellCssAstarToC'),
		),
		array(
			'name'=>'col5',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellCssAstarToC'),
		),
		array(
			'name'=>'col6',
			'header'=>'%<br>A*-G',
			'cssClassExpression'=>array($component,'getCellCssAstarToG'),
		),
		array(
			'name'=>'col7',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellCssAstarToG'),
		),
		array(
			'name'=>'col8',
			'header'=>'Fail',
			'type'=>'raw',
			//'htmlOptions'=>array('width'=>'6%'),
		),
		array(
			'name'=>'col9',
			'header'=>'APS',
			'cssClassExpression'=>array($component,'getCellCssAps'),
			//'htmlOptions'=>array('width'=>'6%'),
		),	
		//Targets	
		array(
			'name'=>'col10',
			'header'=>'A*-A',
			'type'=>'raw',
			'visible'=>$showTargets,
			//'htmlOptions'=>array('width'=>'80px'),
		),
		array(
			'name'=>'col11',
			'header'=>'%',
			'visible'=>$showTargets,
		),
		array(
			'name'=>'col12',
			'header'=>'Target<br>%<br><span class="label">A*-C</span>',
			//'visible'=>false,
			//'htmlOptions'=>array('width'=>'6%'),
		),
		array(
			'name'=>'col13',
			'header'=>'',
			//'type'=>'raw',
			//'htmlOptions'=>array('width'=>'6%'),
		),

		array(
			'name'=>'col14',
			'header'=>'A*-G',
			'type'=>'raw',
			'visible'=>$showTargets,

			//'htmlOptions'=>array('width'=>'80px'),
		),
		array(
			'name'=>'col15',
			'header'=>'%',
			'visible'=>$showTargets,
			//'htmlOptions'=>array('width'=>'80px'),
		),
		array(
			'name'=>'col16',
			'header'=>'APS',
			//'htmlOptions'=>array('width'=>'6%'),
		),
		array(
			'name'=>'col17',
			'header'=>'Total<br>Pupils',
			'type'=>'raw',
			'visible'=>true,
			//'htmlOptions'=>array('width'=>'6%'),
		),
	),
)); ?>