<i class="icon-question-sign"></i> <a href='#' class='show-help'>Show Help</a> 
<?php if($setUpIsComplete):?>
<i class="icon-play-circle"></i> <a href='#' class='start-tour'><strong>Take a Guided Tour</strong></a>
<?php endif;?>
<div class="help-container">
<dl>
<dt>General Information</dt>
<dd>
<p>All columns apart from Mapped Subject can be edited directly by clicking on the <span class="editable">underlined text</span>.
 The <strong>Include</strong> column is saved instantly upon checking/unchecking.</p>
</dd>
<dl>
<dt>Mapped Subject</dt>
<dd>
<p>The mapped subject is the subject name on your MIS that you are pulling the data from. This is very often just the initials
of a subject or a code generated by your MIS.</p>
</dd>
<dt>Subject Name</dt>
<dd>
<p>The subject name is the full and unique name for a mapped subject. It is possible to map the same subject code
to multiple subjects provided the 'Subject Name' is different. You can then filter pupils and classes from subjects
effectively creating multiple unique individual subjects taken by different groups of pupils. See the 'Classes' section below for information
about how to achieve this.</p>
</dd>
<dt>Qualification</dt>
<dd>
<p>Click the link below to show the full list of supported qualifications. The 'Accepted Result' column 
displays the results the system will accept. Any other format of result will count as a fail. You can use the verify button
when reviewing DCPs and Targets to instantly see results for subjects and qualifications that are equal to a fail. 
If you currently use other result formats then contact us and if appropriate we will add them to the list. However, we think we have most of them covered.</p>
<a href="#" id="qualifications-link">Show qualifications</a>
<table class='sticky-table-header'></table>
<div id="sticky-table-container" style="display:none;">
</div>

<p>The list of supported qualifications is mostly based upon the government's latest list of 14-16 Qualifications.
<a target="_blank" href="http://media.education.gov.uk/assets/files/pdf/q/qualifications%20included%20in%20ks4%20performance%20tables%20in%202014.pdf">
here.</a>  The 'Included 2014' column indicates whether the qualification is on this list. If you are running a qualification that is not on the list 
then either let us know so we can update our list or alternatively find the best fit i.e. the qualification with the same
grades and point scores. You can verify all qualifications by visiting the <a target="_blank" href="http://register.ofqual.gov.uk/" > Ofqual Register </a>
and clicking on 'Search Qualifications'. Once you have found the qualification you are looking for you can scroll to the base of the page
and click the 'View Performance Measures' link to view point scores.
</p>
</dd>
<dt>Discount Code</dt>
<dd>
<p>Enter up to 10 characters into this box if the subject requires discounting. The codes can be either
  DfE codes or your own codes. As long as the codes are identical discounting will be applied. Currently discounting only affects the number of grades in a particular 
  range (e.g. 5 x A*-C) and does not affect other measures.<br>

  Please DO NOT add discount codes for subjects of the type English, EngLit, EngLang or Maths. 
  In these special cases more complex discounting can sometimes be applied (See 'Type' below).<br>Note that discounting is only applied when the
report mode is set to '2014 Onwards'.</p>
</dd>
<dt>Volume</dt>
<dd>
<p>The volume column tells the system the amount of GCSE's a subject is worth. The 'Pre 2014' report mode uses this column.</p>
</dd>
</dd>
<dt>Equivalent</dt>
<dd>
<p>The equivalent column tells the system whether the subject is equivalent to a full GCSE(1) or not(0).
 You can enter both a volume and an equivalent and use this data to switch modes when viewing a report. The '2014 Onwards' report mode uses this column.</p>
</dd>
<dt>Type</dt>
<dd>
<p>The type column is used when calculating English and Maths measures as well as the English Baccalaureate. Use the guide below to help select the correct types for
your subjects.</p>
<ul>
<li>English<p>The qualification is new or old specification GCSE English. I.e. not part of a Lit/Lang combination. An A*-C will count towards English measures and the English Baccalaureate</p></li>
<li>EngLang<p>The qualification is part of a Lit/Lang combination. An A*-C will count towards English measures and the English Baccalaureate but only 
  if the pupil is also entered for English Literature (EngLit). PTA will discount appropriately</p></li>
<li>EngLit<p>The qualification is part of a Lit/Lang combination</p></li>
<li>Maths<p>The qualification is Maths. An A*-C in this qualification will count towards Maths measures and the English Baccalaureate. 
  PTA does not currently perform any Maths discounting. This will be reviewed once relevant pilots are completed and reviewed. If this affects you please contact us</p></li>
<li>Additional Science<p>The qualification forms part of a Core/Additional Science combination. An A*-C in both and will count towards the English Baccalaureate</p></li>
<li>Core Science<p>The qualification is part of a Core/Additional Science combination. An A*-C in both and will count towards the English Baccalaureate</p></li>
<li>Biology<p>The qualification is part of a single science Biology/Chemistry/Physics combination. An A*-C in 2 single sciences plus having an entry for all 3 will count towards
the English Baccalaureate</p></li>
<li>Chemistry<p>The qualification is part of a single science Biology/Chemistry/Physics combination.</p></li>
<li>Physics<p>The qualification is part of a single science Biology/Chemistry/Physics combination.</p></li>
<li>Humanity<p>The qualification is Geography or History. An A*-C in either will count towards the English Baccalaureate</p></li>
<li>MFL (Modern Foreign Language)<p>The qualification is a MFL or community language (Applied French and Applied Welsh Second Language do not count).
An A*-C in either a MFL or AFL will count towards the English Baccalaureate</p></li>
<li>AFL (Ancient Foreign Language)<p>The qualification is an AFL</p></li>
</ul>
<p>
  All non Ebacc and non English/Maths subjects should be left as 'None'. </p>
</dd>
<dt>Classes</dt>
<dd>
<p>You can use the classes column to exclude entire classes or individual pupils from classes. When this column displays 'All'
it means that all pupils and classes are included. When this column displays 'Filtered' it means that at least one class or pupil
has been excluded.</p>
</dd>
<dt>Include</dt>
<dd>
<p>Whether to include the subject in reports or not.</p>
</dd>
</dl>
</div>

<?php $qualificationsUrl = Yii::app()->controller->createUrl("ks4qualifications");?>
<?php Yii::app()->clientScript->registerScript("qualifications-help", "
     $('#qualifications-link').toggle(function() {
  		$('#sticky-table-container').load('$qualificationsUrl',function(){
	   		$('.sticky-table-header').show();
	   		if(!$('.sticky-table-header thead').length){
	  		$('#sticky-table-container thead').clone().prependTo('.sticky-table-header');
	  		}
			$('#sticky-table-container thead').hide();
  		}).slideDown();
  		$(this).text('Hide qualifications');
  		return false;
	}, function() {
  		$('#sticky-table-container').slideUp();
  		$('.sticky-table-header').hide();
  		$(this).text('Show qualifications');
  		return false;
	});	

  $('.start-tour').click(function(){
    guiders.show('first');
  })
");?>




