<?php // $gridId, $dataProvider and $component are available to this view
$showTargets=false; //Set to true to display all target columns
$this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>$gridId,
	'template'=>'{items}',
	'nullDisplay'=>'0',
	'dataProvider'=>$dataProvider,
	//'type'=>'condensed',
	'columns'=>array(
			array(
			'name'=>'col1',
			'header'=>'',
			//'htmlOptions'=>array('width'=>'200%'),
			'type'=>'raw'
		),
		array(
			'name'=>'col2',
			'header'=>'%<br>Cohort',
			'value'=>array($component,'getCellValue'),
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
		),
		array(
			'name'=>'col3',
			'header'=>'target',
			'visible'=>$showTargets,
			),
		array(
			'name'=>'col4',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),
		array(
			'name'=>'col5',
			'header'=>'%<br>Pupil<br>Premium',
			'value'=>array($component,'getCellValue'), 
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
			//'htmlOptions'=>array('width'=>'80px'),
		),
		array(
			'name'=>'col6',
			'header'=>'target',
			'visible'=>$showTargets,
			),
		array(
			'name'=>'col7',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),
		array(
			'name'=>'col8',
			'header'=>'%<br>No FSM',
			'value'=>array($component,'getCellValue'),
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
		),
		array(
			'name'=>'col9',
			'header'=>'target',
			'visible'=>$showTargets,
			),
		array(
			'name'=>'col10',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),
		array(
			'name'=>'col11',
			'header'=>'% SEN',
			'value'=>array($component,'getCellValue'),
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
			'type'=>'raw',
		),
		array(
			'name'=>'col12',
			'header'=>'target',
			'visible'=>$showTargets,
			),

		array(
			'name'=>'col13',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),
		array(
			'name'=>'col14',
			'header'=>'% Girls',
			'value'=>array($component,'getCellValue'),
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
			'type'=>'raw',
		),
		array(
			'name'=>'col15',
			'header'=>'target',
			'visible'=>$showTargets,
			),
		array(
			'name'=>'col16',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),
		array(
			'name'=>'col17',
			'header'=>'% Boys',
			'value'=>array($component,'getCellValue'),
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
			'type'=>'raw',
		),
		array(
			'name'=>'col18',
			'header'=>'target',
			'visible'=>$showTargets,
			),
		array(
			'name'=>'col19',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),
		array(
			'name'=>'col20',
			'header'=>'% EAL',
			'value'=>array($component,'getCellValue'),
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
			'type'=>'raw',
		),
		array(
			'name'=>'col21',
			'header'=>'target',
			'visible'=>$showTargets,
			),
		array(
			'name'=>'col22',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),
		array(
			'name'=>'col23',
			'header'=>'% CLA',
			'value'=>array($component,'getCellValue'),
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
			'type'=>'raw',
		),
		array(
			'name'=>'col24',
			'header'=>'target',
			'visible'=>$showTargets,
			),
		array(
			'name'=>'col25',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),
		array(
			'name'=>'col26',
			'header'=>'% Ethnic<br>Minority',
			'value'=>array($component,'getCellValue'),
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellTrafficLightCss'),
		),
		array(
			'name'=>'col27',
			'header'=>'target',
			'visible'=>$showTargets,
			),
		array(
			'name'=>'col28',
			'header'=>'',
			'type'=>'raw',
			'cssClassExpression'=>array($component,'getCellButtonTrafficLightCss'),
		),

		
	),
)); ?>